set nocompatible
syntax on
setlocal iskeyword+=-
" Setting
set relativenumber
set clipboard=unnamedplus
" set nohlsearch
set number
set smarttab
set cindent
set tabstop=4
set shiftwidth=4
set expandtab
set encoding=utf-8
set fileencoding=utf-8
set hidden
set updatetime=300
set shortmess+=A
set signcolumn=yes
